version: "3.7"
services:
  db:
    container_name: database
    restart: always
    image: king_roger
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: RobotBoy
      POSTGRES_PASSWORD: RobotBoy  # To be moved to environment file
      POSTGRES_DATABASE: KingRoger
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql
    networks:
      - database-postgraphile
  graphql:
    image: albiberto/node-postgraphile
    container_name: postgraphile
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://RobotBoy:RobotBoy@db:5432/KingRoger # To be moved to environment file
      PORT: 5000
    expose:
      - 5000
    ports:
      - 8080:5000
    links:
      - db
    networks:
      - database-postgraphile
networks:
  database-postgraphile: